[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = [
  "-C",
  "target-feature=+atomics,+bulk-memory,+mutable-globals",
  "-C",
  "link-arg=--max-memory=4294967296",
  "--cfg",
  "getrandom_backend=\"wasm_js\"",
]
